[build]
  publish = "."

[[redirects]]
  from = "https://kmmp.org/*"
  to = "https://www.kmmp.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200